name: Build
on: [push, pull_request]
jobs:
  build:
    strategy:
      matrix:
        java: [8, 11, 17]
    runs-on: ubuntu-20.04
    container:
      image: openjdk:${{ matrix.java }}-jdk
      options: --user root
    steps:
      - uses: actions/checkout@v1
      - uses: gradle/wrapper-validation-action@v1
      - run: ./gradlew build --stacktrace
      - name: Archive test results
        if: "${{ always() }}"
        uses: actions/upload-artifact@v2
        with:
          name: "test-results-java${{ matrix.java }}"
          path: |
            build/reports/
            */build/reports/